#!/bin/bash

set -o errexit -o nounset -o pipefail

status=0

for mirror in $(cat /etc/mirrors); do
    echo
    echo Deploying to $mirror
    echo

    rsync -acv --delete --fsync --preallocate /etc/letsencrypt/ $mirror:/etc/letsencrypt &&
        ssh root@$mirror "systemctl is-active --quiet nginx.service && systemctl reload nginx; if systemctl is-active --quiet dnsdist.service; then dnsdist -c -e 'reloadAllCertificates()'; end" ||
        status=1
done

exit $status
