#!/bin/bash

. shared.sh
. hosts.sh

for host in ${hosts_web[@]}; do
    remote=root@$host

    echo
    echo $host
    echo

    ssh $remote ln -snf /usr/lib/nginx/modules/ /etc/nginx/modules

    rsync etc/systemd/system/{session-ticket-keys-create.service,session-ticket-keys-rotate.service,session-ticket-keys-rotate.timer} $remote:/etc/systemd/system/
    rsync --chmod=755 session-ticket-keys-create session-ticket-keys-rotate $remote:/usr/local/bin/
    rsync -r --delete etc/systemd/system/nginx.service.d $remote:/etc/systemd/system/
    rsync etc/syslog-ng/conf.d/nginx.conf $remote:/etc/syslog-ng/conf.d/
    rsync etc/logrotate.d/nginx $remote:/etc/logrotate.d/

    ssh $remote 'syslog-ng-ctl reload &&
mkdir -pm755 /var/cache/nginx &&
groupadd -fr tls &&
mkdir -pm 750 /etc/tls/session-ticket-keys &&
chmod 750 /etc/tls &&
chown root:tls /etc/tls &&
systemctl daemon-reload &&
systemctl enable --now session-ticket-keys-create.service session-ticket-keys-rotate.timer nginx.service &&
chmod 700 /var/log/nginx'
done
