#!/bin/bash

. shared.sh
. hosts.sh

for host in ${hosts_all[@]}; do
    remote=root@$host

    echo
    echo $host
    echo

    tmp="$(mktmp journald.conf)"
    cp etc/systemd/journald.conf "$tmp"
    sed -i "s/{{journald_system_max_use}}/${hosts_journald_system_max_use[$host]:-4G}/g" "$tmp"
    sed -i "s/{{journald_system_max_file_size}}/${hosts_journald_system_max_file_size[$host]:-256M}/g" "$tmp"
    rsync "$tmp" $remote:/etc/systemd/journald.conf
    rm "$tmp"
    ssh $remote 'systemctl disable --now systemd-journald-audit.socket &&
systemctl reload systemd-journald'

    rsync -r --delete etc/systemd/system/syslog-ng@default.service.d $remote:/etc/systemd/system/
    rsync etc/syslog-ng/syslog-ng.conf $remote:/etc/syslog-ng/
    ssh $remote 'mkdir -p /etc/syslog-ng/conf.d &&
systemctl daemon-reload &&
systemctl enable --now syslog-ng@default.service &&
syslog-ng-ctl reload'

    rsync etc/logrotate.conf $remote:/etc/
    ssh $remote 'rm -vf /etc/logrotate.d/{chrony,syslog-ng}'
    rsync -r --delete etc/systemd/system/logrotate.timer.d $remote:/etc/systemd/system/
    ssh $remote 'systemctl daemon-reload &&
systemctl enable --now logrotate.timer'
done
