#!/bin/bash

. shared.sh
. hosts.sh

for host in ${hosts_all[@]}; do
    remote=root@$host

    echo
    echo $host
    echo

    password=$(head -c22 <(tr -dc A-Za-z0-9 </dev/random))
    echo $password > passwords/$host
    echo "root:$password" | ssh $remote chpasswd
done
