#!/bin/bash

. shared.sh
. hosts.sh

for host in ${hosts_primary[@]}; do
    remote=root@$host

    echo
    echo $host
    echo

    rsync --chmod=F755 certbot-replicate session-ticket-keys-sync $remote:/usr/local/bin/
    rsync etc/systemd/system/certbot-renew.service.d/replicate.conf $remote:/etc/systemd/system/certbot-renew.service.d/
    rsync etc/systemd/system/session-ticket-keys-sync.{service,timer} $remote:/etc/systemd/system/
    ssh $remote systemctl daemon-reload
    ssh $remote systemctl enable --now session-ticket-keys-sync.timer
done
