#!/bin/bash

. shared.sh
. hosts.sh

for host in ${hosts_web[@]}; do
    remote=root@$host

    echo
    echo $host
    echo

    ssh $remote ln -snf /usr/lib/nginx/modules/ /etc/nginx/modules

    rsync etc/systemd/system/{session-ticket-keys-create.service,session-ticket-keys-rotate.service,session-ticket-keys-rotate.timer} $remote:/etc/systemd/system/
    rsync --chmod=755 session-ticket-keys-create session-ticket-keys-rotate $remote:/usr/local/bin/
    rsync -r --delete etc/systemd/system/nginx.service.d/ $remote:/etc/systemd/system/nginx.service.d

    ssh $remote "mkdir -pm755 /var/cache/nginx
groupadd -fg 2100 tls
mkdir -p -m 750 /etc/session-ticket-keys && chgrp tls /etc/session-ticket-keys
systemctl daemon-reload &&
systemctl enable session-ticket-keys-create.service session-ticket-keys-rotate.timer nginx"
done
