#!/bin/bash

. shared.sh
. hosts.sh

for host in ${hosts_all[@]}; do
    remote=root@$host

    echo
    echo $host
    echo

    rsync -r --delete etc/systemd/network/$host/ $remote:/etc/systemd/network/
    if [[ $host != @(dal.grapheneos.org|fra.grapheneos.org|yto.grapheneos.org) ]]; then
        rsync etc/systemd/networkd.conf.simple $remote:/etc/systemd/networkd.conf
    else
        rsync etc/systemd/networkd.conf.forward $remote:/etc/systemd/networkd.conf
    fi
    ssh $remote 'systemctl enable systemd-networkd.service &&
systemctl disable --now systemd-network-generator.service systemd-networkd-resolve-hook.socket &&
systemctl restart systemd-networkd.service'

    fq=etc/systemd/system/$host.fq.service
    [[ -f $fq ]] || fq=etc/systemd/system/single.fq.service
    if [[ ${hosts_type[$host]:-vps} != container ]]; then
        rsync $fq $remote:/etc/systemd/system/fq.service
        ssh $remote systemctl enable fq.service
    fi

    if [[ $host = @(dal.grapheneos.org|fra.grapheneos.org|yto.grapheneos.org) ]]; then
        rsync etc/bird/$host.bird.conf $remote:/etc/bird.conf
    fi

    rsync etc/resolv.conf $remote:/etc/
    rsync etc/unbound/unbound.conf $remote:/etc/unbound/
    rsync -r --delete etc/systemd/system/unbound.service.d $remote:/etc/systemd/system/
    ssh $remote 'systemctl daemon-reload &&
systemctl disable --now systemd-resolved.service &&
systemctl enable unbound.service &&
systemctl restart unbound.service'

    rsync --chmod=755 tcp-fastopen-rotate-keys $remote:/usr/local/bin/
    rsync etc/systemd/system/tcp-fastopen-rotate-keys.{service,timer} $remote:/etc/systemd/system/
    ssh $remote systemctl enable --now tcp-fastopen-rotate-keys.timer
done
