#!/bin/bash

. shared.sh
. hosts.sh

for host in ${hosts_all[@]}; do
    remote=root@$host

    echo
    echo $host
    echo

    hostname=${hosts_hostname[$host]}

    ssh $remote hostnamectl hostname $hostname

    tmp=$(mktmp hosts)
    cp etc/hosts $tmp
    sed -i "s/{{fqdn}}/$host/; s/{{hostname}}/$hostname/" $tmp
    rsync $tmp $remote:/etc/hosts
    rm $tmp
done
