#!/bin/bash

set -o errexit -o nounset -o pipefail

[[ $# -eq 0 ]] || exit 1

. hosts.sh

for host in ${hosts_all[@]}; do
    echo $host
    echo

    ssh root@$host -O exit || true
    ssh root@$host -O exit true || true

    echo
done
