#!/bin/bash

set -o errexit -o nounset -o pipefail

user=root

. hosts.sh

rm -rf modules packages units
mkdir -p modules packages units

for host in ${hosts_all[@]}; do
    (
        ssh root@$host lsmod | awk '{ print $1 }' | sort > modules/$host
        ssh root@$host pacman -Qqe > packages/$host
        ssh root@$host systemctl list-unit-files --state=enabled --state=disabled --state=masked | sort > units/$host
        ssh root@$host sysctl -a | sort > sysctl/$host
    ) &
done

wait
