#!/bin/bash

set -o errexit

user=root

. hosts.sh

rm -rf modules packages units
mkdir -p modules packages units

for host in ${hosts_all[@]}; do
    (
        ssh root@$host lsmod | sort > modules/$host
        ssh root@$host pacman -Qqe > packages/$host
        ssh root@$host systemctl list-unit-files --state=enabled --state=disabled --state=masked | sort > units/$host
    ) &
done

wait
