#!/bin/bash

set -o errexit -o nounset -o pipefail

umask 077

mkdir -p /etc/nginx/session-ticket-keys
mount -t tmpfs -o size=1M,mode=700,noswap tmpfs /etc/nginx/session-ticket-keys

cd /etc/nginx/session-ticket-keys

for i in {1..4}; do
    head -c 80 </dev/random >$i.key
done
