#!/bin/bash

set -o errexit -o nounset -o pipefail

umask 077

mkdir -p /etc/nginx/session-ticket-keys
mount -t ramfs -o mode=700 ramfs /etc/nginx/session-ticket-keys

cd /etc/nginx/session-ticket-keys

openssl rand -out 1.key 80
openssl rand -out 2.key 80
openssl rand -out 3.key 80
openssl rand -out 4.key 80
