#!/bin/bash

set -o errexit -o nounset -o pipefail

[[ $# -eq 1 ]] || exit 1

user=root

. hosts.sh

declare -n hosts=hosts_$1
for host in ${hosts[@]}; do
    echo $host
    echo

    ssh $user@$host curl -sS --unix-socket /run/nginx/status.sock http://localhost/
    echo
done
