#!/bin/bash

set -o errexit -o nounset -o pipefail

[[ $# -eq 2 ]] || exit 1

input=
read -p "Reboot $1 servers with $2 second delay? " input
if [[ $input != yes ]]; then
    exit 1
fi
echo

user=root

. hosts.sh

declare -n hosts=hosts_$1
for host in ${hosts[@]}; do
    echo $host
    echo

    ssh root@$host 'if systemctl is-active bird.service >/dev/null; systemctl stop bird.service && sleep 5; end'
    systemctl -H $host reboot
    sleep $2

    echo
done
