#!/bin/bash

set -o errexit -o nounset -o pipefail

cd /etc/session-ticket-keys

rsync -I 2.key 1.key
rsync -I 3.key 2.key
rsync -I 4.key 3.key
head -c 80 </dev/random >new.key
rsync -I new.key 4.key
rm new.key
nginx -s reload
