define public_ipv4 = 87.249.129.100;
define public_ipv6 = 2a02:6ea0:c75f::1;
define neighbor_as = 4200060068;
define neighbor_rs1_ipv4 = 185.59.223.4;
define neighbor_rs1_ipv6 = 2a02:6ea0:c400::100;
define neighbor_rs2_ipv4 = 213.155.129.101;
define neighbor_rs2_ipv6 = 2001:2035:0:1bcb::2;
define neighbor_rs3_ipv4 = 156.146.35.215;
define neighbor_rs3_ipv6 = 2a02:6ea0:d300::100;

filter grapheneos_filter {
    accept;
}

filter ns2_filter {
    if net = 23.149.125.0/24 || net ~ [2602:f4d9:1::/48, 2602:f4d9:3::/48] then {
        bgp_path.delete(64512);
        bgp_path.prepend(40806);
        accept;
    }

    reject;
}

log syslog all;
debug protocols all;

router id public_ipv4;

protocol device {
    scan time 10;
}

template bgp grapheneos {
    local as 40806;
    graceful restart on;
    hold time 60;
    connect delay time 0;
    connect retry time 5;
}

protocol bgp datapacket_ipv4_rs1 from grapheneos {
    multihop 64;
    source address public_ipv4;
    neighbor neighbor_rs1_ipv4 as neighbor_as;
    ipv4 {
        import none;
        export filter grapheneos_filter;
    };
}

protocol bgp datapacket_ipv6_rs1 from grapheneos {
    multihop 64;
    source address public_ipv6;
    neighbor neighbor_rs1_ipv6 as neighbor_as;
    ipv6 {
        import none;
        export filter grapheneos_filter;
    };
}

protocol bgp datapacket_ipv4_rs2 from grapheneos {
    multihop 64;
    source address public_ipv4;
    neighbor neighbor_rs2_ipv4 as neighbor_as;
    ipv4 {
        import none;
        export filter grapheneos_filter;
    };
}

protocol bgp datapacket_ipv6_rs2 from grapheneos {
    multihop 64;
    source address public_ipv6;
    neighbor neighbor_rs2_ipv6 as neighbor_as;
    ipv6 {
        import none;
        export filter grapheneos_filter;
    };
}

protocol bgp datapacket_ipv4_rs3 from grapheneos {
    multihop 64;
    source address public_ipv4;
    neighbor neighbor_rs3_ipv4 as neighbor_as;
    ipv4 {
        import none;
        export filter grapheneos_filter;
    };
}

protocol bgp datapacket_ipv6_rs3 from grapheneos {
    multihop 64;
    source address public_ipv6;
    neighbor neighbor_rs3_ipv6 as neighbor_as;
    ipv6 {
        import none;
        export filter grapheneos_filter;
    };
}

protocol bgp ns2_ipv4 from grapheneos {
    multihop 1;
    source address 87.249.129.100;
    neighbor 87.249.129.102 as 64512;
    passive;
    ipv4 {
        import filter ns2_filter;
        export none;
    };
}

protocol bgp ns2_ipv6 from grapheneos {
    multihop 1;
    source address 2a02:6ea0:c75f::1;
    neighbor 2a02:6ea0:c75f:1::1 as 64512;
    passive;
    ipv6 {
        import filter ns2_filter;
        export none;
    };
}
