server:
    private-domain: zen.spamhaus.org
    private-domain: rep.mailspike.net
    private-domain: bl.score.senderscore.com
    private-domain: score.senderscore.com
    private-domain: bl.spameatingmonkey.net
    private-domain: bl.ipv6.spameatingmonkey.net
    private-domain: list.dnswl.org
    private-domain: bip.virusfree.cz
    private-domain: bl.blocklist.de
    private-domain: dwl.dnswl.org
    private-domain: email.rspamd.com
    private-domain: ebl.msbl.org
    private-domain: multi.surbl.org
    private-domain: hashbl.surbl.org
    private-domain: multi.uribl.com
    private-domain: uribl.rspamd.com
    private-domain: dbl.spamhaus.org
    private-domain: zen.spamhaus.org
    private-domain: uribl.spameatingmonkey.net
    private-domain: fresh15.spameatingmonkey.net

    private-domain: bl.spamcop.net
    private-domain: b.barracudacentral.org
