blacklist ata_generic
blacklist ata_piix
blacklist cfg80211
blacklist floppy
blacklist intel_agp
blacklist intel_rapl_common
blacklist intel_rapl_msr
blacklist ip_tables
blacklist joydev
blacklist kvm_amd
blacklist kvm_intel
blacklist mac_hid
blacklist mousedev
blacklist pata_acpi
blacklist pcspkr
blacklist psmouse
blacklist qemu_fw_cfg
blacklist rapl
blacklist serio_raw
blacklist snd_hda_intel
blacklist snd_intel8x0
blacklist sr_mod
blacklist virtio_balloon
blacklist virtio_console
blacklist vmw_vsock_virtio_transport
blacklist vmw_vsock_vmci_transport
blacklist vsock_loopback
