net.core.devconf_inherit_init_net = 3

net.core.wmem_max=4194304
net.core.rmem_max=4194304

net.netfilter.nf_conntrack_expect_max = 1

kernel.yama.ptrace_scope = 2

vm.mmap_rnd_bits = 32
vm.mmap_rnd_compat_bits = 16

vm.memfd_noexec = 1

kernel.kptr_restrict = 2

kernel.unprivileged_userns_clone = 0

kernel.unprivileged_bpf_disabled = 1
net.core.bpf_jit_harden = 2

kernel.io_uring_disabled = 1
kernel.io_uring_group = 2000

kernel.kexec_load_disabled = 1

fs.protected_regular = 2
fs.protected_fifos = 2

kernel.panic = -1
kernel.panic_on_oops = 1

dev.tty.ldisc_autoload = 0

fs.binfmt_misc.status = 0
